### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by rj-d2** [goofyMagpie8/bluploader#1]
hi i tried to get this running on my seedbox, i dont know much about python, every help is welcome,

~/.apps/bluploader.py upload -h
  File "/homexx/user/.apps/bluploader.py", line 156
    path=f'"{path}"'
                   ^
SyntaxError: invalid syntax

**Comment by excludedBittern8** [comment]
Yeah it might be the verison of python I need to update the documentation

**Comment by goofyMagpie8** [comment]
Please use python 3.6 or higher
